### ISSUE TITLE
Ne projesi lan bu :D

### ISSUE THREAD

**Issue by bartukocakara** [AtaAksoy/aksoydev#1]

**Comment by AtaAksoy** [comment]
Sunucu aldim amazondan denemeler yapiyorum :)

**Comment by bartukocakara** [comment]
Amazon sağlam yolar yalnız işin bitince kart bilgini değiştir xd

**Comment by AtaAksoy** [comment]
Yok ben almadım iş yaptığımız bir abi sağ olsun 1 sene ücretsiz hediye etti :)
